local register_firework_node = fireworks_reimagined.register_firework_node
register_firework_node(nil, "sphere", nil, nil, nil, true)
register_firework_node(nil, "star", nil, nil, nil, true)
register_firework_node(nil, "ring", nil, nil, nil, true)
register_firework_node(nil, "burst", nil, nil, nil, true)
register_firework_node(nil, "cube", nil, nil, nil, true)
register_firework_node(nil, "spiral", nil, nil, nil, true)
register_firework_node(nil, "chaotic", nil, nil, nil, nil)
register_firework_node(nil, "flame", nil, nil, nil, true)
register_firework_node(nil, "snowflake", nil, nil, nil, true)
register_firework_node(nil, "christmas_tree", nil, nil, nil, true)
register_firework_node(nil, "present", nil, nil, nil, true)
register_firework_node(nil, "hour_glass", nil, nil, nil, true)
